# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
	config.vm.define :proyecto do |proyecto|
	proyecto.vm.box = "bento/ubuntu-22.04"
	proyecto.vm.network :private_network, ip: "192.168.50.3"
	proyecto.vm.hostname = "proyecto"
	proyecto.vm.provision "shell", path: "scriptProxy.sh"
	proyecto.vm.provider "virtualbox" do |vb|
    	  vb.memory = "1024"
  end	
 end
 	config.vm.define :backend1 do |backend1|
	backend1.vm.box = "bento/ubuntu-22.04"
	backend1.vm.network :private_network, ip: "192.168.50.4"
	backend1.vm.hostname = "backend1"
	backend1.vm.synced_folder "./Sincronizado","/Sincronizado"
	backend1.vm.provision "shell", path: "scriptBackend.sh"
	backend1.vm.provider "virtualbox" do |vb|
    	  vb.memory = "1024"
  end	
 end
 	config.vm.define :backend2 do |backend2|
	backend2.vm.box = "bento/ubuntu-22.04"
	backend2.vm.network :private_network, ip: "192.168.50.5"
	backend2.vm.hostname = "backend2"
	backend2.vm.synced_folder "./Sincronizado","/Sincronizado"
	backend2.vm.provision "shell", path: "scriptBackend.sh"
	backend2.vm.provider "virtualbox" do |vb|
     	 vb.memory = "1024"
  end
end

	config.vm.define :backend3 do |backend3|
	backend3.vm.box = "bento/ubuntu-22.04"
	backend3.vm.network :private_network, ip: "192.168.50.6"
	backend3.vm.hostname = "backend3"
	backend3.vm.synced_folder "./Sincronizado","/Sincronizado"
	backend3.vm.provision "shell", path: "scriptBackend.sh"
	backend3.vm.provider "virtualbox" do |vb|
     	 vb.memory = "1024"
  end
end

end



